### PR TITLE
BUGFIX: Accept a string as second parameter of the slot method

### PR DESCRIPTION
**Pull request by daniellienert**
Fixes: #42

### CODE REVIEW

**Comment by daniellienert** [comment]
@kdambekalns, currently testing against Neos 7. I remember that there have been changes in Signal/Slot information passing. May that be related?

**Comment by kdambekalns** [comment]
Hah, this seems to be a prime example of why the "maybe this passes a string" idea was bad. My guess: deactivating the signal information in the connecion is the better fix!

**Comment by kdambekalns** [comment]
… which you seem to do in https://github.com/neos/content-repository-search/blob/895ca8fa8bb9ee373dcc4c76a05b743ff3950e80/Classes/Package.php#L59 already!?

Also, #42 is weird, the signal information is passed _twice_?!

**Comment by daniellienert** [comment]
@kdambekalns, wild guess from looking at it: 

there is a loop over the slots in `dispatch` and signal information is added to the `$signalArguments[]` array on every loop:
https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/SignalSlot/Dispatcher.php#L182

As the common `nodeAdded` signal is used. Might it be that `$passSignalInformation` is set to true at two other connections to that signal and so they are passed here as well?

**Comment by albe** [comment]
> https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/SignalSlot/Dispatcher.php#L182

That line is indeed a bug! The `$signalArguments` array needs to be reset to the initial value passed into the `dispatch` for every iteration.

**Comment by albe** [comment]
Should be fixed with https://github.com/neos/flow-development-collection/pull/2362 so this can then be closed. Sorry that change in behaviour went by unnoticed!

**Review by kdambekalns — CHANGES_REQUESTED** [review]
I still think this is wrong. The parameter must be a `Workspace` (or `null`), but never something else. So removing the type does not solve anything!

**Comment by daniellienert** [comment]
Hey @kdambekalns, no worries. Just fixed it here to get the project going. The fix in Flow makes this unnecessary.

**Pull request closed without merging**
